# Generated by Django 3.1.4 on 2020-12-10 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='PostData',
        ),
    ]
